- name: Add auto-registration key
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server"
    attribute: "agentAutoRegisterKey"
    value: "388b633a88de126531afa41eff9aa69e"

- name: Configure artifacts directory
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server/artifacts/artifactsDir"
    value: artifacts1

- name: Configure purge settings
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server/artifacts/purgeSettings"

- name: Configure purgeStartDiskSpace
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server/artifacts/purgeSettings/purgeStartDiskSpace"
    value: "2.0"

- name: Configure purgeUptoDiskSpace
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server/artifacts/purgeSettings/purgeUptoDiskSpace"
    value: "5.0"

- name: Configure site urls
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server/siteUrls"

- name: Configure site url
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server/siteUrls/siteUrl"
    value: "http://gocd.example.com"

- name: Configure secureSiteUrl
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server/siteUrls/secureSiteUrl"
    value: "https://gocd.example.com"

- name: Restart and enable go-server service
  become: yes      
  systemd:
    name: go-server
    enabled: yes
    daemon-reload: yes
    state: restarted

- name: Wait for the GoCD server to start
  uri:
    url: http://127.0.0.1:8153/go/pipelines
    follow_redirects: yes
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  when: not ansible_check_mode
  retries: 30
  delay: 2
