- name: Setup gocd repo
  become: yes
  copy:
    dest: /etc/yum.repos.d/gocd.repo
    src: gocd.repo
    owner: root
    group: root
    mode: 0444

- name: Create go group
  become: yes
  group:
    name: go
    gid: "{{ gogid }}"
    system: yes
    
- name: Create go user
  become: yes
  user:
    name: go
    comment: GoCD User
    uid: "{{ gouid }}"
    group: go
    shell: /bin/bash
    home: /var/go
    create_home: yes

- name: Setup data directory
  become: yes
  file:
    path: "{{ item }}"
    owner: go
    group: go
    mode: 0750
    state: directory
  with_items:
    - /data
    - /data/var-log-go-server
    - /data/var-lib-go-server

- name: Create symlinks
  become: yes
  file:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    force: yes
    state: link
    owner: go
    group: go
  with_items:
    - {'src': '/data/var-lib-go-server', 'path': '/var/lib/go-server' }
    - {'src': '/data/var-log-go-server', 'path': '/var/log/go-server' }

- name: Install required packages
  become: yes
  package:
    name: 
      - git
      - python-lxml
      - python-requests
      - python-passlib
      - httpd-tools
      - go-server-20.3.0-11530

- name: Start gocd server
  include_tasks: restart.yml
  vars:
    state: started

- name: Install external plugins
  include_tasks: plugins.yml

- name: Setup admin user
  include_tasks: admin.yml

- name: Setup backup
  include_tasks: backup.yml

- name: Add auto-registration key
  become: yes
  xml:
    path: "/etc/go/cruise-config.xml"
    xpath: "/cruise/server"
    attribute: "agentAutoRegisterKey"
    value: "{{ agentAutoRegisterKey }}"

- name: Configure artifacts
  become: yes
  gocd_api:
    domain: "{{ domain }}"
    config_type: 'artifacts'
    username: "{{ adminUsername }}"
    password: "{{ adminPassword }}"
    data: "{{ artifactsData }}"

- name: Configure default job timeout
  become: yes
  gocd_api:
    domain: "{{ domain }}"
    config_type: 'default_job_timeout'
    username: "{{ adminUsername }}"
    password: "{{ adminPassword }}"
    data: "{{ defaultJobTimeoutData }}"

- name: Configure pipeline-groups
  become: yes
  gocd_api:
    domain: "{{ domain }}"
    config_type: 'pipeline_groups'
    entity_id: "{{ item.name }}"
    username: "{{ adminUsername }}"
    password: "{{ adminPassword }}"
    data: "{{ item }}"
  with_items: "{{ pipelineGroupsData }}"

#- include: nginx.yml